#!/usr/bin/env node

const {createLogger, transports, format} = require('winston');
const {execSync} = require('child_process');
const moment = require('moment');
const path = require('path');
const pm2 = require('pm2');
const fs = require('fs');

// Resolve the teleboard main
const mainPath = path.join(__dirname, 'dist/server/main.js');
const mainFile = path.normalize(mainPath);
const colorGreen = '\x1b[32m';
const colorCyan = '\x1b[36m';
const colorReset = '\x1b[0m';

// Create a simple colorized logger
function makeLogger(json) {
	return createLogger({
		level: "debug",
		transports: [
			new transports.Console({
				format: json ? format.json() : format.combine(
					format.colorize(),
					format.printf(info => {
						return `> ${info.level}: ${info.message}`;
					})
				)
			})
		]
	});
}

// Utility to convert memory sizes
function bytesToSize(bytes) {
   var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
   if (bytes == 0) return '0 Byte';
   var i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
   return Math.round(bytes / Math.pow(1024, i), 2) + ' ' + sizes[i];
}

// Launch teleboard with pm2
function startTeleboard(input) {
	const logger = makeLogger(input.json);

	const handleErr = (err) => {
		if(!err) return false;
		
		logger.error('Error during daemon initialization: ', err);
		pm2.disconnect();
		return true;
	}

	logger.info('Received startup request...');

	pm2.connect((err) => {
		if(handleErr(err)) return;

		logger.info('Starting teleboard daemon...');

		pm2.start(mainFile, {autorestart: false}, (err, proc) => {
			if(err) {
				if(err.toString().startsWith('Error: Script already launched')) {
					logger.warn('Teleboard is already running!');
					pm2.disconnect();
					return;
				} else {
					if(handleErr(err)) return;
				}
			}

			pm2.describe(proc[0]['pm_id'], (err, desc) => {
				if(handleErr(err)) return;

				logger.info('Successfully started Teleboard');
				logger.info('- Use '+colorCyan+'teleboard status'+colorReset+' to view process information');
				logger.info('- Use '+colorCyan+'teleboard stop'+colorReset+' to terminate teleboard');
				
				pm2.disconnect();
			});
		});
	});
}

// Stop the active teleboard process
function stopTeleboard(input) {
	const logger = makeLogger(input.json);
	const mainFile = path.normalize(mainPath);

	const handleErr = (err) => {
		if(!err) return false;
		
		logger.error('Error during daemon connection: ', err);
		pm2.disconnect();
		return true;
	}

	pm2.connect((err) => {
		if(handleErr(err)) return;

		pm2.list((err, res) => {
			if(handleErr(err)) return;

			let theProc = null;
			
			res.forEach(proc => {
				if(proc.pm2_env.pm_exec_path == mainFile) {
					theProc = proc;
				}
			});

			if(theProc && theProc['pm2_env'].status == 'online') {
				const id = theProc['pm_id'];

				pm2.stop(id, (err) => {
					if(handleErr(err)) return;

					logger.info('Successfully terminated Teleboard');
					pm2.disconnect();
				});
			} else {
				logger.warn('Teleboard is not currently running');
				pm2.disconnect();
			}
		});
	});
}

// Print out the daemon status
function showStatus(input) {
	const logger = makeLogger(input.json);

	const handleErr = (err) => {
		if(!err) return false;
		
		logger.error('Error during daemon connection: ', err);
		pm2.disconnect();
		return true;
	}

	pm2.connect((err) => {
		if(handleErr(err)) return;

		pm2.list((err, res) => {
			if(handleErr(err)) return;

			let theProc = null;
			
			res.forEach(proc => {
				if(proc.pm2_env.pm_exec_path == mainFile) {
					theProc = proc;
				}
			});

			if(theProc && theProc['pm2_env'].status == 'online') {
				const monitor = theProc.monit;
				const uptime = Date.now() - theProc['pm2_env'].created_at;

				logger.info('Teleboard is up and running!');
				logger.info('');
				logger.info('Memory: ' + colorCyan + bytesToSize(monitor.memory) + colorReset);
				logger.info('Cpu:    ' + colorCyan + monitor.cpu + '%' + colorReset);
				logger.info('Uptime: ' + colorCyan + moment.duration(uptime).humanize() + colorReset);
			} else {
				logger.warn('Teleboard is not currently running');
			}

			pm2.disconnect();
		});
	});
}

// Start the Teleboard server in the foreground
function runTeleboard(input) {
	const logger = makeLogger(input.json);

	logger.info('Starting Teleboard as foreground process...')

	require(mainFile);
}

// Execute the server and client build commands
function buildTeleboard(input) {
	const logger = makeLogger(input.json);
	const then = Date.now();

	logger.info('Compiling server and client files...');

	execSync('npm run build:server && npm run test:server && npm run build:client', {stdio: 'inherit'});

	const duration = Date.now() - then;

	logger.info('Server & Client compiling successful!'+colorGreen+' ('+duration+'ms)'+colorReset);
	logger.info('');
	logger.info('- Teleboard can now be started with'+colorCyan+' teleboard start'+colorReset);
	logger.info('- Run teleboard directly with'+colorCyan+' teleboard run'+colorReset);
}

// Print out the config JSON
function showConfig() {
	const productionConfig = path.join(__dirname, 'data/config.json');
	const defaultConfig = path.join(__dirname, 'data/config.default.json');

	if(fs.existsSync(productionConfig)) {
		console.log(fs.readFileSync(productionConfig, 'utf8'));
	} else {
		console.log(fs.readFileSync(defaultConfig, 'utf8'));
	}
}

// Handle the command input
require('yargs')
	.scriptName("teleboard")
	.usage('$0 <cmd> [options]')
	.default('help')
	.command({
		command: 'start',
		desc: 'Launch the Teleboard server',
		handler: startTeleboard
	})
	.command({
		command: 'stop',
		desc: 'Terminate the Teleboard server',
		handler: stopTeleboard
	})
	.command({
		command: 'status',
		desc: 'Show the current daemon status',
		handler: showStatus
	})
	.command({
		command: 'run',
		desc: 'Start the Teleboard server in the foreground',
		handler: runTeleboard
	})
	.command({
		command: 'config',
		desc: 'Display the Teleboard config',
		handler: showConfig
	})
	.command({
		command: 'compile',
		desc: 'Build & test the teleboard server and client',
		handler: buildTeleboard
	})
	.option('json', {
		desc: 'Print out all messages in JSON form'
	})
	.help()
	.demandCommand()
	.strict()
	.parse()