#!/usr/bin/env node

const { join } = require('path');
const { existsSync } = require('fs');
const { execSync } = require('child_process');
const consola = require('consola');

const entrypoint = join(__dirname, 'packages/vindigo-cli/dist/index.js');

if(!existsSync(entrypoint)) {
	consola.info('Missing CLI distribution files, building...');

	try {
		consola.info('Generating server files...');
		execSync('yarn workspace vindigo-server build');

		consola.info('Generating CLI files...');
		execSync('yarn workspace vindigo-cli build');
	} catch(err) {
		console.error('Failed to build CLI distribution files');
	}
}

try {
	require(entrypoint);
} catch(err) {
	console.error('Failed to initialize CLI');
	throw err;
}