# This is the main Vindigo configuration file
# used to customize and configure your installation
# of Vindigo. Please resort to the upgrade guide on
# how to keep your configuration up to date.

name = "Vindigo"
debug = false
hostname = "localhost"
port = 8045
maintenance = false
check_version = true
logfile = "vindigo.log"
palette = [
    { name = "Peter River", value = "#3498db"},
    { name = "Alizarin", value = "#e74c3c"},
    { name = "Emerald", value = "#2ecc71"},
    { name = "Turquoise", value = "#1abc9c"},
    { name = "Amethyst", value = "#9b59b6"},
    { name = "Asphalt", value = "#34495e"},
    { name = "Sun Flower", value = "#f1c40f"}
]

[email]
address = ""
domain = ""
user_name = ""
password = ""
port = 25

[database]
driver = "sqlite"
hostname = "localhost"
port = 3306
username = "vindigo"
password = ""
name = "vindigo"
path = "./database.sqlite"